[package]
name = "komec"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = [
  "crates/ast",
  "crates/lsp",
  "crates/parser",
  "crates/runtime",
  "crates/semantics",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
kome_ast = { path = "crates/ast" }
kome_parser = { path = "crates/parser" }
kome_semantics = { path = "crates/semantics" }
kome_runtime = { path = "crates/runtime" }

[dependencies]
kome_ast.workspace = true
kome_parser.workspace = true
kome_semantics.workspace = true
kome_runtime.workspace = true

serde = { version = "1", features = ["derive"] }
toml = "1.1.2+spec-1.1.0"